/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Comandos;
import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author workstation
 */
public class Pricipal extends javax.swing.JFrame {

    /**
     * Creates new form Pricipal
     */
    Comandos cmdos = new Comandos();

    String comando = "";
    boolean onEdit = false;

    public Pricipal() {
        initComponents();
        cmdos.setDirectorioActual("C:\\");
        txtAreaConsola.setText(cmdos.getDirectorioActual() + ">");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaConsola = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtAreaConsola.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaConsola.setColumns(20);
        txtAreaConsola.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        txtAreaConsola.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaConsola.setRows(5);
        txtAreaConsola.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAreaConsola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaConsolaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaConsolaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtAreaConsola);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consola", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setViewportView(jTree1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visual", jPanel2);

        jLabel1.setText("Comiladores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaConsolaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaConsolaKeyTyped
        // TODO add your handling code here:
//        System.out.println(evt.getKeyChar());


    }//GEN-LAST:event_txtAreaConsolaKeyTyped

    private void txtAreaConsolaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaConsolaKeyPressed
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        System.out.println(evt.getExtendedKeyCode());
        String respuesta = "";
        if (evt.getExtendedKeyCode() == 10) {
//            System.out.print(cmdos.getDirectorioActual() + ">");
            comando = txtAreaConsola.getText().substring(txtAreaConsola.getText().lastIndexOf(">") + 1, txtAreaConsola.getText().length());
            String entradaTeclado = comando; //Invocamos un método sobre un objeto Scanner
            String[] comandoCompleto = entradaTeclado.split(" ");
//            System.out.println(comandoCompleto.length);
            switch (comandoCompleto.length) {
                case 1:
                    if (comandoCompleto[0].equals("")) {
                        break;
                    }
                    respuesta = cmdos.ejecutarComado(comandoCompleto[0]);
                    if (respuesta.equals(cmdos.getLimpiar_pantalla())) {
                        txtAreaConsola.setText(null);
//                        System.out.println("entro");
                    } else if (!respuesta.equals("")) {

                        txtAreaConsola.setText(txtAreaConsola.getText() + "\n" + respuesta);

                    }

                    break;
                case 2:
                    respuesta = cmdos.ejecutarComado(comandoCompleto[0], comandoCompleto[1]);

                    if (comandoCompleto[0].equals(cmdos.getEditar_contenido_archivo()) && !respuesta.equals("El archivo que quiere editar no existe.")) {
                        onEdit = true;
//                        System.out.println("entro");
                        String resp = respuesta.equals("null") ? "" : respuesta;
                        txtAreaConsola.setText(txtAreaConsola.getText() + "\n" + resp);
                    } else if (!respuesta.equals("")) {

                        txtAreaConsola.setText(txtAreaConsola.getText() + "\n" + respuesta);
                    }

                    break;

                case 3:
                    respuesta = cmdos.ejecutarComado(comandoCompleto[0], comandoCompleto[1], comandoCompleto[2]);
                    if (!respuesta.equals("")) {

                        txtAreaConsola.setText(txtAreaConsola.getText() + "\n" + respuesta);
                    }

                    break;
                default:

            }
//            System.out.println(letra.equals(""));
            comando = "";
            if (comando.equals("")) {
                String textoAnteriro = txtAreaConsola.getText();
                if (!onEdit) {
                    txtAreaConsola.setText(textoAnteriro + (!textoAnteriro.equals("") ? "\n" : "") + cmdos.getDirectorioActual() + ">");
                }
            }

            int cartet = txtAreaConsola.getText().lastIndexOf("");
            if (!onEdit) {

                txtAreaConsola.setCaretPosition(cartet + 1);
            }

        }
//        else if (!letra.equals("") && evt.getExtendedKeyCode() != 8 && !letra.equals("￿")) {
//            comando += evt.getKeyChar();
//            System.out.println(comando);
//        }

    }//GEN-LAST:event_txtAreaConsolaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextArea txtAreaConsola;
    // End of variables declaration//GEN-END:variables
}
